name: Build TKMetaStripper Dylib

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
    - name: 1. 检出代码
      uses: actions/checkout@v4

    - name: 2. 安装底层编译依赖 (ldid & dpkg)
      run: |
        brew install ldid dpkg

    - name: 3. 安装 Theos 框架
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS

    - name: 4. 安装 iOS SDKs (处理默认空文件夹冲突)
      run: |
        rm -rf $THEOS/sdks
        git clone https://github.com/theos/sdks.git $THEOS/sdks

    - name: 5. 编译高安全无符号脱壳版 (Release)
      run: |
        make clean
        make FINALPACKAGE=1

    - name: 6. 提取纯净 .dylib 并生成下载
      uses: actions/upload-artifact@v4
      with:
        name: TKMetaStripper_Release_Dylib
        path: .theos/obj/**/TKMetaStripper.dylib
